### ISSUE TITLE
Running with two stereo cameras

### ISSUE THREAD

**Issue by jorgemiar** [introlab/dotmask#1]
I'm running RTAB-Map with two ZED cameras at the same time (front and back of robot) and now considering adding this to remove dynamic objects from the map. Have you tried running this with two cameras? Do you think it would be possible if I ran two instances of the dotmask node? Or what would be the best approach?

**Comment by j20100** [comment]
I am able to run two instances of dotmask at the same time. However, I only have one camera at hand (asus xtion) so both instances are subscribed to the same image topic. If you are already using two zed cameras with RTAB-Map I see no problem running a dotmask instance for each camera.

**Comment by jorgemiar** [comment]
Ok, I'll give it a try, thanks! 

In terms of launching the files, I'm also on Melodic and I already have a catkin_ws with my zed and rtabmap launch files, should I move those to the python3 ws? Or are you overlaying workspaces when running `source ~/catkin_ws_py3/devel/setup.bash`?

**Comment by j20100** [comment]
This project is based on python3, however ROS melodic does not work well with python3. That's why the project uses a workspace dedicated to python3. 

RTAB-map and the zed cameras should be in the catkin_ws and dotmask in the catkin_ws_py3. Also, make sure to source the right catkin workspace when launching each nodes.

In your RTAB-map launch file, the topics should be remaped to correspond to the dotmask topics (see dotmask-zed.launch).
